[options]
HoldPkg = pacman glibc
Architecture = aarch64
CheckSpace
ParallelDownloads = 5
DownloadUser = alpm
DisableSandboxFilesystem
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[forge]
Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
